[general]
# Lower values = more yellow/orange. 
# Neutral is 6500. 3500-4000 is noticeably yellow.
temp-day=4500
temp-night=3000

# Optional: adjust brightness if it's too intense (0.1 to 1.0)
brightness-day=1.0
brightness-night=0.8

location-provider=manual

[manual]
lat=19.07
lon=72.87
