# Core Colors
background            #19120c
foreground            #eee0d5
selection_foreground  #fbba74
selection_background  #492900
cursor                #fbba74
cursor_text_color     #19120c

# Regular Colors
color0  #19120c
color1  #ffb4ab
color2  #fbba74
color3  #becc9b
color4  #ffdcbc
color5  #feddbe
color6  #e1c1a3
color7  #eee0d5

# Bright Colors
color8  #403830
color9  #ffb4ab
color10 #fbba74
color11 #becc9b
color12 #ffdcbc
color13 #feddbe 
color14 #e1c1a3
color15 #eee0d5
