font_family JetBrainsMono NF Bold
font_size 9.0
bold_font auto
italic_font auto
bold_italic_font auto

background_opacity 0.9
confirm_os_window_close 0

shell_integration enabled
shell_integration enabled no-cursor

# Animated cursor
cursor_trail 1

# change to x11 or wayland or leave auto
linux_display_server auto

scrollback_lines 2000
wheel_scroll_min_lines 1

enable_audio_bell no

window_padding_width 4

include colors.conf
map f1 show_last_visited_command_output

map ctrl+shift+a show_last_command_output
map ctrl+shift+g launch --type=overlay --stdin-source=@last_cmd_output nvim -u NONE -c "set buftype=nofile" -c "set clipboard=unnamedplus" -c "nnoremap q :q!<CR>" -

